#!/usr/bin/env node
'use strict'

const meow = require('meow')
const isSemver = require('is-semver')
const update = require('update-notifier')
const publish = require('./lib/publish')
require('colorful').toxic()

const cli = meow(`
${`Usage:`.bold}

  -t/--test:         Custom test command
  -p/--push:         Push to remote git server only
  -v--version:       Output version number
  -h/--help:         Output help infomation
`, {
  alias: {
    t: 'test',
    v: 'version',
    h: 'help',
    p: 'push'
  }
})

update({pkg: cli.pkg}).notify()

if (cli.flags.version) {
  console.log(cli.pkg.version)
  process.exit()
}

// for all semantic version
const allTypes = [
  'patch',
  'minor',
  'major',
  'premajor',
  'preminor',
  'prepatch',
  'prerelease',
  'from-git'
]
const type = cli.input[0] || 'patch'

if (isSemver(type) || allTypes.indexOf(type) > -1) {
  publish(type, cli)
}
